version: '3'
services:
  jupyter:
    build:
      context : .
      dockerfile: Dockerfile.jupyter
    volume:
    - ..:/workspace:cached
    ports:
    - "8888:8888"
    command: jupyter lab --ip=0.0.0.0" --allow-root --no-browser --NotebookApp.token='MLOPSPROJ'
    network_mode: service:another-service

  mlflow:
    image: Dockerfile.mlflow
    ports:
      - "5000:5000"