version: "3.9"
name: "5mlde-v1"
services:
  api:
    build: api
    ports:
      - 8086:8086
    volumes:
      - models:/mlflow
    depends_on:
      - mlflow
  training:
      build: training
      ports:
        - "4200:4200"
      volumes:
        - models:/mlflow
  mlflow:
      build: mlflow
      ports:
        - "5000:5000"
      volumes:
        - models:/mlflow
      depends_on:
        - training

volumes:
  models: