version: "3.9"
name: "5mlde-v1"
services:
  api:
    build: api
    ports:
      - 8086:8086
    volumes:
      - 5mlde:/mlflow
    depends_on:
      - mlflow
      
  training:
      build: training
      ports:
        - "4200:4200"
      volumes:
        - 5mlde:/mlflow

  mlflow:
      build: mlflow
      ports:
        - "5000:5000"
      volumes:
        - 5mlde:/mlflow
      depends_on:
        - training

  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./performance:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://api:8086
  
  worker:
    image: locustio/locust
    volumes:
      - ./performance:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./monitoring/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yml

volumes:
  5mlde: